os: osx
osx_image: xcode9.3
sudo: false

language: java

git:
  submodules: false

before_install:
  - git submodule update --init --remote --recursive

install:
  - echo "Override default Travis install step to avoid unnecessary './gradlew assemble'."

branches:
  only:
    - master
    - /^release\/.+$/
    - develop
    - /^feature\/.+$/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - test
  - name: dev_build
    if: branch =~ /^release\/.+$/
  - name: build
    if: branch = master

jobs:
  include:
    - stage: test
      script: gradle junitPlatformTest
    - stage: dev_build
      script: gradle jfxNative
    - stage: build
      script: gradle jfxNative
