# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- develop
- release/*
- refs/tags/*

jobs:

- job: Test

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:

  - task: Bash@3
    displayName: OpenJDK Install
    inputs:
      targetType: 'filePath'
      filePath: azure-jdk-install.sh

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '1.8'
      jdkArchitectureOption: x64
      jdkSourceOption: localDirectory
      jdkFile: $(Agent.ToolsDirectory)/jdk-8u191-linux-x64.tar.gz
      jdkDestinationDirectory: $(Agent.ToolsDirectory)/Java8

  - task: Gradle@2
    displayName: Gradle Test
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      tasks: 'junitPlatformTest'


- job: Java
  condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'

  - task: Bash@3
    displayName: OpenJDK Install
    inputs:
      targetType: 'filePath'
      filePath: azure-jdk-install.sh

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '1.8'
      jdkArchitectureOption: x64
      jdkSourceOption: localDirectory
      jdkFile: $(Agent.ToolsDirectory)/jdk-8u191-linux-x64.tar.gz
      jdkDestinationDirectory: $(Agent.ToolsDirectory)/Java8

  - script: git submodule update --init --remote --recursive

  - task: Gradle@2
    displayName: Gradle Build
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      tasks: 'bootJar'

  - task: PublishPiplineArtifact@0
    inputs:
      artifactName: 'PSA'
      targetPath: 'build/libs'