# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master
  - develop
  - release/*
  - hotfix/*
  - feature/*

pr:
  - master
  - develop
  - release/*

variables:
  profileProd: prod
  psaJavaArtifact: psaJava
  frontendArtifact: Frontend
  frontendDir: app/frontend
  ubuntu: Ubuntu-18.04

stages:
  - stage: analyze_test_build
    displayName: 'Analyze, test, build'
    jobs:
      - job: Backend
        pool:
          vmImage: $(ubuntu)

        steps:
          - script: printenv
          - task: Gradle@2
            displayName: 'Test backend'
            inputs:
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.8
              jdkArchitectureOption: x64
              tasks: 'junitPlatformTest'

      - job: Frontend
        pool:
          vmImage: $(ubuntu)

        steps:
          - task: NodeTool@0
            displayName: 'Setup environment'
            inputs:
              versionSpec: '10.x'
          - script: printenv

          - script: npm ci
            displayName: 'Install dependencies'
            workingDirectory: $(frontendDir)

          - script: npm run lint
            displayName: 'Lint'
            workingDirectory: $(frontendDir)

          - script: npm run test -- --watch=false
            displayName: 'Run tests'
            workingDirectory: $(frontendDir)

          - script: npm run build:prod
            displayName: 'Build frontend'
            workingDirectory: $(frontendDir)

          - publish: $(System.DefaultWorkingDirectory)/app/frontend/dist/frontend
            displayName: 'Publish Frontend'
            artifact: $(frontendArtifact)

  - stage: build
    displayName: 'Build / Package'
    jobs:
      - job: Package

        pool:
          vmImage: $(ubuntu)

        steps:
          - task: Gradle@2
            displayName: 'Setup Environment'
            inputs:
              javaHomeOptions: JDKVersion
              jdkVersionOption: 1.8
              jdkArchitecture: x64
          - script: printenv

          - download: current
            artifact: $(frontendArtifact)
            displayName: 'Download Frontend'

          - task: CopyFiles@2
            displayName: 'Copy Frontend to java resources'
            inputs:
              sourceFolder: $(Pipeline.Workspace)/$(frontendArtifact)
              targetFolder: "app/starter/src/main/resources/public/app"

          - script: ./gradlew :app:starter:bootJar
            displayName: 'Package App'
            env:
              spring_profiles_active: $(profileProd)

          - publish: $(System.DefaultWorkingDirectory)/app/starter/build/libs
            displayName: 'Publish Jar'
            artifact: $(psaJavaArtifact)

  - stage: e2e_tesing
    displayName: 'e2e tests'
    jobs:
      - job: e2e

        pool:
          vmImage: $(ubuntu)

        steps:
          - task: Gradle@2
            displayName: 'Setup Environment'
            name: Versions
            inputs:
              javaHomeOptions: JDKVersion
              jdkVersionOption: 1.8
              jdkArchitecture: x64
              tasks: 'setPipelineVariables'

          - download: current
            artifact: $(psaJavaArtifact)
            displayName: 'Download PSA Java'

          - task: CopyFiles@2
            displayName: 'Copy PSA Java to distributions'
            inputs:
              sourceFolder: $(Pipeline.Workspace)/$(psaJavaArtifact)
              contents: '*.jar'
              targetFolder: "distribution/docker/psa-test"

          - task: Docker@2
            displayName: 'Build e2e Docker Image'
            inputs:
              command: build
              repository: 'billedtrain380/psa'
              buildContext: distribution/docker/psa-test/
              arguments: '--build-arg PSA_VERSION=$(fullVersion)'
              tags: '$(dockerTag)'

          - script: 'docker run -d --name psa-test -p 8080:8080 billedtrain380/psa:$(dockerTag)'
            displayName: 'Run psa-test docker image'

          - task: NodeTool@0
            displayName: 'Setup environment'
            inputs:
              versionSpec: '10.x'

          - script: npm ci
            displayName: 'Install dependencies'
            workingDirectory: $(frontendDir)

          - script: npm run e2e:ci
            displayName: 'Run e2e tests'
            workingDirectory: $(frontendDir)
            env:
              LT_USERNAME: $(LT_USERNAME)
              LT_ACCESS_KEY: $(LT_ACCESS_KEY)
              FULL_VERSION: $(fullVersion)

          - script: docker rm psa-test
            displayName: 'Remove psa test docker image'

  - stage: build_push_docker_image
    displayName: 'Build / Push Docker Image'
    condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    jobs:
      - job: build_push_docker_image
        displayName: 'Build / Push Docker Image'

        pool:
          vmIMage: $(ubuntu)

        steps:
          - task: Gradle@2
            displayName: 'Setup Environment'
            name: Versions
            inputs:
              javaHomeOptions: JDKVersion
              jdkVersionOption: 1.8
              jdkArchitecture: x64
              tasks: 'setPipelineVariables'

          - script: printenv
          - script: |
              echo "PSA version: $(version)"
              echo "PSA full version: $(fullVersion)"
              echo "PSA docker tag: $(dockerTag)"
            displayName: Print Versions

          - download: current
            artifact: $(psaJavaArtifact)
            displayName: 'Download PSA Java'

          - task: CopyFiles@2
            displayName: 'Copy PSA Java to distributions'
            inputs:
              sourceFolder: $(Pipeline.Workspace)/$(psaJavaArtifact)
              contents: '*.jar'
              targetFolder: "distribution/docker/psa"

          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: 'BilledTrain380 Docker Hub'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              containerRegistry: 'BilledTrain380 Docker Hub'
              repository: 'billedtrain380/psa'
              buildContext: distribution/docker/psa/
              arguments: '--build-arg PSA_VERSION=$(fullVersion)'
              tags: '$(dockerTag)'

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: push
              containerRegistry: 'BilledTrain380 Docker Hub'
              repository: 'billedtrain380/psa'
              tags: '$(dockerTag)'

