ALTER TABLE PARTICIPANT
    ALTER COLUMN birthday
        RENAME TO old_birthday;

ALTER TABLE PARTICIPANT
    ADD COLUMN birthday DATE NOT NULL DEFAULT CURRENT_DATE();


UPDATE PARTICIPANT AS t1
SET birthday = (
    SELECT FORMATDATETIME(DATEADD('SECOND', t2.old_birthday / 1000, DATE '1970-01-01'), 'yyyy-MM-dd')
    FROM PARTICIPANT AS t2
    WHERE t2.id = t1.id
    );

ALTER TABLE PARTICIPANT
    DROP COLUMN old_birthday;
